"""empty message

Revision ID: 149c3a75f405
Revises: af5ad15ac08f
Create Date: 2023-07-03 17:33:29.226042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '149c3a75f405'
down_revision = 'af5ad15ac08f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pokemon',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('base_experience', sa.Integer(), nullable=False),
    sa.Column('ability', sa.String(), nullable=False),
    sa.Column('sprite', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('team',
    sa.Column('trainer_id', sa.Integer(), nullable=True),
    sa.Column('pokemon_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['pokemon_name'], ['pokemon.name'], ),
    sa.ForeignKeyConstraint(['trainer_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team')
    op.drop_table('pokemon')
    # ### end Alembic commands ###
